# Generated by Django 4.1.4 on 2023-01-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('item_description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchaseOrderID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('qtyNeeded', models.PositiveIntegerField()),
                ('qtyProvided', models.PositiveIntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('poStatus', models.CharField(max_length=20)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotationID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('totalPrice', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('validityDate', models.DateField()),
                ('qtyProvided', models.PositiveIntegerField(null=True)),
                ('quotationStatus', models.CharField(max_length=20)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=20, null=True)),
                ('vendorAddress', models.CharField(max_length=100, null=True)),
                ('vendorContact', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('itemID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=40, null=True)),
                ('quantity', models.PositiveIntegerField(default=None, null=True)),
                ('itemPriceperUnit', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('quotationID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quotation')),
                ('vendorID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='staffID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('productID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=40, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('productPriceperUnit', models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True)),
                ('purchaseOrderID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.purchaseorder')),
                ('vendorID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quotationID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.quotation'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='staffID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.vendor'),
        ),
    ]
