# Generated by Django 4.1.4 on 2023-01-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='productPurchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='itemPurchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='poStatus',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
