# Generated by Django 4.1.4 on 2023-01-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_staff_vendor_quotationitem_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
