# Generated by Django 4.1.4 on 2023-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_purchaseorderproduct_productpurchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='productName',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='productPriceperUnit',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
