# Generated by Django 4.1.4 on 2023-01-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_purchaseorder_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='itemID',
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='purchaseOrderID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.purchaseorder'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotationID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quotation'),
        ),
    ]
