# Generated by Django 4.1.4 on 2023-01-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_purchaseorder_qtyneeded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='quantity',
        ),
    ]
