# Generated by Django 4.1.4 on 2023-01-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_purchaseorderproduct_quantity_quotationitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='qtyProvided',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='vendorID',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='itemFinalPrice',
            field=models.FloatField(default=None, null=True),
        ),
    ]
