# Generated by Django 4.1.4 on 2023-01-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_quotation_qtyprovided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='qtyProvided',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='qtyProvided',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
